language: go

os: 
  - linux
  - windows
  - osx

dist: xenial

go:
  - 1.x
  - "1.10"
  - 1.11.x
  - master

matrix:
  exclude:
  - go: master
    os: windows 

install: true

script:
  - env GOPATH=$(pwd) go build indole
